services:
  postgres:
    image: postgres:16-alpine
    container_name: dashboard-postgres
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local